# https://docs.travis-ci.com/user/languages/r
language: r
# dist: trusty
# precise vs trusty as of Jan 2017. Use old environment for testing old compilers, R?
# trusty will only work with sudo: true for now
# https://ropensci.org/blog/2016/07/12/travis-osx
# https://docs.travis-ci.com/user/ci-environment/

sudo: false
cache: packages

addons:
  apt:
    packages:
      - r-cran-rodbc
      - unixodbc-dev

r:
  - oldrel
  - release
  - devel

matrix:
  allow_failures:
    - r: oldrel

repos:
  CRAN: https://cloud.r-project.org

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

warnings_are_errors: true

env:
  - OMP_NUM_THREADS=1 CFLAGS="-O0 -Werror -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable" CXXFLAGS="-O0 -Werror -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable" R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=FALSE
  - OMP_NUM_THREADS=2 CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native" R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=FALSE

before_script:
 - ls -aR
 - rm .Rinstignore  # do install everything for testing
 - sed -i.old1 '/.*[Dd]ata.*/d' .Rbuildignore # do include data for testing
 - sed -i.old2 '/\.covrignore/d' .Rbuildignore
 - sed -i.old3 '/\.lintr/d' .Rbuildignore
 - rm .Rbuildignore.old{1,2,3}
 - Rscript -e "Rcpp::compileAttributes()"


after_success:
 - ls -aR
 - cat ./icd.Rcheck/tests/test-all.Rout
 - Rscript -e "covr::codecov(quiet = FALSE)"

notifications:
  email:
    on_success: change
    on_failure: change
