# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# temporarily disable cache if error?
cache:
- C:\RLibrary

# Adapt as necessary starting from here

platform:
  - x86
  - x64

before_build:
#  - ls -aR
  - rm .Rinstignore  # do install everything for testing
  - sed -i'' -e '/.*[Dd]ata.*/d' .Rbuildignore # do include data for testing, some data not in github though
  # make sure Rcpp generated code is made, if not checked in to repo
  - Rscript -e "install.packages(c('remotes', 'Rcpp', 'knitr'), repos = 'https://cloud.r-project.org/'); Rcpp::compileAttributes()"
  # temporarily used while latest icd.data is not on CRAN
  #- Rscript -e "remotes::install_github(\"jackwasey/icd.data\", ref = \"WHO\")"
  # CRAN of course doesn't do this, but Travis has build without nhds available
  - Rscript -e "remotes::install_github(\"jackwasey/nhds\")"

build_script:
  - travis-tool.sh install_deps

environment:
  # APPVEYOR_CACHE_SKIP_RESTORE: true
  WARNINGS_ARE_ERRORS: 1
  _R_CHECK_EXIT_ON_FIRST_ERROR_: true
  USE_RTOOLS: true
  R_BUILD_ARGS: ""
  NOT_CRAN: true
  matrix:
    - R_VERSION: release
      MINI_BENCH: "yes"
    - R_VERSION: devel
    - ICD_DATA_VERBOSE: true
    - ICD_DATA_OFFLINE: true
    - ICD_DATA_INTERACT: false
# by default, don't set environment, to be more like CRAN?
#  ICD_DATA_ABSENT_ACTION: 'message'

matrix:
  fast_finish: true
  allow_failures:
    - platform: x64
      MINI_BENCH: "yes"
  exclude:
    - platform: x86
      MINI_BENCH: "yes"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

after_build:
  - pwd
  - IF NOT "%MINI_BENCH%"=="" cd benchmarks/icd-JSS3447-replication
  - IF NOT "%MINI_BENCH%"=="" make bench3
#  - IF NOT "%MINI_BENCH%"=="" make replmat # needs to call Rscript on appveyor path.
  - IF NOT "%MINI_BENCH%"=="" cd ../..

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
 - provider: Email
   to:
     - appveyor@jackwasey.com
#   subject: 'r-appveyor build {{status}}'                  # optional
#   message: "https://ci.appveyor.com/project/krlmlr/r-appveyor"    # optional
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true
